name: npm-install

on:
  push:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: 18.15.0
      - name: Cache
        uses: actions/cache@v3
        env:
          cache-name: cache-nx
        with:
          path: ./baserepo/node_modules/.cache/nx
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
      - name: npm install and test 
        working-directory: ./baserepo
        run: |
          yarn install
          yarn setup
